start_date: 2022-12-01T00:00:00 
end_date: 2022-12-02T18:00:00   
timestep: 6h
run_name: uwcw

checkpoint_path: /pfs/lustrep4/scratch/project_465000527/buurmans/DE_330_WP14/Anemoi/checkpoints/b546d2ac348e4ffb946ca488095f14d1/inference-last.ckpt
leadtimes: 12 # Number of leadtimes in each forecast 
frequency: 6h 

global:         
  dataset: ${hardware.paths.data}/aifs-od-an-oper-0001-mars-n320-2019-2023-6h-v6.zarr
  start: 2022-06-01
  end: 2023-05-31
#new
dataset:
  cutout:
    - dataset: ${hardware.paths.data}${hardware.files.dataset_lam}
    - dataset: ${hardware.paths.data}${hardware.files.dataset}
  adjust: all
  drop:
    - q_600
    - t_600
    - u_600
    - v_600
    - z_600
    - w_50
    - w_100
    - w_150
    - w_200
    - w_250
    - w_300
    - w_400
    - w_500
    - w_600
    - w_700
    - w_850
    - w_925
    - w_1000
  reorder:
    - 10u
    - 10v
    - 2d
    - 2t
    - cos_julian_day
    - cos_latitude
    - cos_local_time
    - cos_longitude
    - insolation
    - lsm
    - msl
    - q_100
    - q_1000
    - q_150
    - q_200
    - q_250
    - q_300
    - q_400
    - q_50
    - q_500
    - q_700
    - q_850
    - q_925
    - sin_julian_day
    - sin_latitude
    - sin_local_time
    - sin_longitude
    - skt
    - sp
    - t_100
    - t_1000
    - t_150
    - t_200
    - t_250
    - t_300
    - t_400
    - t_50
    - t_500
    - t_700
    - t_850
    - t_925
    - tp
    - u_100
    - u_1000
    - u_150
    - u_200
    - u_250
    - u_300
    - u_400
    - u_50
    - u_500
    - u_700
    - u_850
    - u_925
    - v_100
    - v_1000
    - v_150
    - v_200
    - v_250
    - v_300
    - v_400
    - v_50
    - v_500
    - v_700
    - v_850
    - v_925
    - z_100
    - z_1000
    - z_150
    - z_200
    - z_250
    - z_300
    - z_400
    - z_50
    - z_500
    - z_700
    - z_850
    - z_925
    - z
  min_distance_km: 0
  statistics: ${hardware.paths.data}${hardware.files.dataset}

# graph: /pfs/lustrep4/scratch/project_465000527/buurmans/DE_330_WP14/Anemoi/multi-domain-training/output/graphs/AA.pt
# graph: /pfs/lustrep4/scratch/project_465000527/buurmans/DE_330_WP14/Anemoi/multi-domain-training/OUTPUT_OLD_3_5graphs/AA.pt
workdir: /pfs/lustrep4/scratch/project_465000527/multi-domain/inference/output/temp #Used to store temporary files for verif output

dataloader:
  datamodule:
    _target_: bris.data.dataset.NativeGridDataset
    _convert_: all


# Optional dataloader settings
#  prefetch_factor: 2 
num_workers: 1

hardware:
  paths:
    output: ${output}
    workdir: ${workdir}
    data: /pfs/lustrep4/scratch/project_465000527/anemoi/datasets/
  files:
    dataset: ERA5/aifs-od-an-oper-0001-mars-n320-2019-2023-6h-v6.zarr
    # dataset: ERA5/aifs-od-an-oper-0001-mars-o96-2016-2023-6h-v6.zarr
    dataset_lam: UWC_WEST/uwcwest-rr-an-oper-0001-mars-2p0km-2020-2023-6h-v2-knmi.zarr
  num_gpus_per_node: 8
  num_gpus_per_model: 8
  num_nodes: 1
  graph_label: None

# If the user wants to release GPU cache and memory
# This option releases unused cached/memory used by torch
release_cache: False

model:
  _target_: bris.model.BrisPredictor
  _convert_: all

output: /pfs/lustrep4/scratch/project_465000527/buurmans/DE_330_WP14/Anemoi/bris_inference/output/UWCW/ #Not a required field, used in output path in routing

routing:
  - decoder_index: 0
    domain_index: 0
    outputs:
      # Forecasts
      - netcdf:
          filename_pattern: ${output}/pred_%Y%m%dT%HZ.nc
          variables: [2t, msl]
          extra_variables: [ws] #Compute wind speed from 10u and 10v
      # # Verification against observatins (stored in a verif netcdf file)
      # - verif:
      #     filename: ${output}/verif/t2m/VERIF_FILENAME.nc 
      #     variable: 2t
      #     elev_gradient: -0.0065 #Height correction
      #     units: degC
      #     obs_sources:
      #       - verif:
      #           filename: PATH_TO_VERIF_FILE #Verif file with observations
      # Point verification against analysis (typically use the inference dataset with thinning)
      # - verif:
      #     filename: ${output}/verif/2t.nc
      #     variable: 2t
      #     elev_gradient: -0.0065 #Height correction
      #     units: degC
      #     obs_sources:
      #       - verif:
      #           filename: /pfs/lustrep4/scratch/project_465000527/nipentho/verification/nordic/6h/202206_202305/t2m/MEPS_2.5km.nc
      # - verif:
      #     filename: ${output}/verif/msl.nc
      #     variable: msl
      #     units: hPa
      #     obs_sources:
      #       - verif:
      #           filename: /pfs/lustrep4/scratch/project_465000527/nipentho/verification/nordic/6h/202206_202305/mslp/MEPS_2.5km.nc
      # - verif:
      #     filename: ${output}/verif/tp.nc
      #     variable: tp
      #     units: mm
      #     obs_sources:
      #       - verif:
      #           filename: /pfs/lustrep4/scratch/project_465000527/nipentho/verification/nordic/6h/202206_202305/precip6h/MEPS_2.5km.nc
      # - verif:
      #     filename: ${output}/verif/ws.nc
      #     variable: ws
      #     units: m/s
      #     obs_sources:
      #       - verif:
      #           filename: /pfs/lustrep4/scratch/project_465000527/nipentho/verification/nordic/6h/202206_202305/ws10m/MEPS_2.5km.nc

#Add outputs for decoder_index 0, domain_index 1 for global domain

verif_dataset: 
  dataset: /pfs/lustrep4/scratch/project_465000527/anemoi/datasets/MEPS/aifs-meps-2.5km-2020-2024-6h-v6.zarr
  thinning: 16
