start_date: 2022-09-24T00:00:00
end_date: 2022-09-24T00:00:00

checkpoints:
  forecaster:
    checkpoint_path: /leonardo_work/EUHPC_R04_079/mingstad/experiments/fcast/checkpoint/e3787dd78d06453292d2d86c4a05220a/inference-last.ckpt
    leadtimes: 32
  interpolator:
    checkpoint_path: /leonardo_work/EUHPC_R04_079/mingstad/experiments/interp/checkpoint/0450788390ea4e13acf912acb29a042c/inference-last.ckpt #72842ae194f14cff9e108258c4bf1881/inference-last.ckpt
    leadtimes: 31
    static_forcings_dataset: ${dataset}

global_land_dataset: ${datasets}/aifs-ea-an-oper-0001-mars-n320-1979-2023-6h-v1-land.zarr 
global_atm_dataset: ${datasets}/aifs-ea-an-oper-0001-mars-n320-1979-2022-6h-v6.zarr


workdir: /leonardo_work/EUHPC_R04_079/mingstad/inference/workdir/
datasets: /leonardo_work/DestE_340_25/ai-ml/datasets/
output: /leonardo_work/EUHPC_R04_079/mingstad/inference/

dataset:
  dataset: 
    join:
      - dataset: ${global_atm_dataset}
      - dataset: ${global_land_dataset}
        select: ["lcc", "mcc", "hcc", "tcc", "strd", "ssrd"]
    adjust: ["start", "end"]
  select: ['10u', '10v', '2d', '2t', 'cos_julian_day', 'cos_latitude', 'cos_local_time', 'cos_longitude', 'hcc', 'insolation', 'lcc', 'lsm', 'mcc', 'msl', 'q_100', 'q_1000', 'q_150', 'q_200', 'q_250', 'q_300', 'q_400', 'q_50', 'q_500', 'q_700', 'q_850', 'q_925', 'sin_julian_day', 'sin_latitude', 'sin_local_time', 'sin_longitude', 'skt', 'sp', 'ssrd', 'strd', 't_100', 't_1000', 't_150', 't_200', 't_250', 't_300', 't_400', 't_50', 't_500', 't_700', 't_850', 't_925', 'tcc', 'tcw', 'tp', 'u_100', 'u_1000', 'u_150', 'u_200', 'u_250', 'u_300', 'u_400', 'u_50', 'u_500', 'u_700', 'u_850', 'u_925', 'v_100', 'v_1000', 'v_150', 'v_200', 'v_250', 'v_300', 'v_400', 'v_50', 'v_500', 'v_700', 'v_850', 'v_925', 'w_100', 'w_1000', 'w_150', 'w_200', 'w_250', 'w_300', 'w_400', 'w_50', 'w_500', 'w_700', 'w_850', 'w_925', 'z', 'z_100', 'z_1000', 'z_150', 'z_200', 'z_250', 'z_300', 'z_400', 'z_50', 'z_500', 'z_700', 'z_850', 'z_925']
  reorder: sort

  # dataset:
  #   join:
  #   - dataset: ${global_atm_dataset}
  #     drop: ["sdor", "slor", "cp", "u_600", "v_600", "z_600", "t_600", "q_600", "w_600"]
  #   - dataset: ${global_land_dataset}
  #     select: ["lcc", "mcc", "hcc", "tcc", "strd", "ssrd"]
  #   adjust: ["start", "end"]
  #   reorder: sort
  # select: ${select}

frequency: 6h

verif_folder: /leonardo_work/EUHPC_R04_079/bris/verification/nordic/1h/202206_202305/
verif_name: n320_6hfc_1hi.nc #cs1536_n320.nc #cs1536_o96.nc #cs1536_o96.nc #cloudy_skies_o96.nc
verif_name_load: IFS_9km.nc

# dataset_verif:
#   join:
#   - dataset: ${global_atm_dataset}
#     drop: ["sdor", "slor", "cp", "u_600", "v_600", "z_600", "t_600", "q_600", "w_600"]
#   - dataset: ${global_land_dataset}
#     select: ["lcc", "mcc", "tcc", "strd", "ssrd"]
#   adjust: ["start", "end"]
#   reorder: sort


# If the user wants to release GPU cache and memory
# This option releases unused cached/memory used by torch
release_cache: False

# Determine how much the encoder and decoder is chunked
inference_num_chunks: 1

dataloader:
  datamodule:
    _target_: bris.data.dataset.NativeGridDataset
    _convert_: all

hardware:

  num_gpus_per_node: 4
  num_gpus_per_model: 4
  num_nodes: 1


model:
  _target_: bris.model.Interpolator
  _convert_: all


routing:
  - decoder_index: 0
    domain_index: 0
    outputs:
      - netcdf:
          filename_pattern: ${output}/ian_v2_%Y%m%dT%HZ.nc
          variables: [2t, msl, tp, lcc, mcc, hcc, tcc, 2d]
          extra_variables: [ws] 
          domain_name: meps
          interp_res: 0.25
      # - verif:
      #     filename: ${verif_folder}/t2m/${verif_name}
      #     variable: 2t
      #     units: degC
      #     elev_gradient: -0.0065
      #     obs_sources:
      #       - verif:
      #           filename: ${verif_folder}/t2m/${verif_name_load}
      # - verif:
      #     filename: ${verif_folder}/ws10m/${verif_name}
      #     variable: ws
      #     units: m/s
      #     obs_sources:
      #       - verif:
      #           filename: ${verif_folder}/ws10m/${verif_name_load}
      # - verif:
      #     filename: ${verif_folder}/mslp/${verif_name}
      #     variable: msl
      #     units: hPa
      #     obs_sources:
      #       - verif:
      #           filename: ${verif_folder}/mslp/${verif_name_load}
      # - verif:
      #     filename: ${verif_folder}/precip1h/${verif_name}
      #     variable: tp
      #     units: mm
      #     obs_sources:
      #       - verif:
      #           filename: ${verif_folder}/precip1h/${verif_name_load}
