start_date: ${run_iso}
end_date: ${run_iso}

checkpoints:
  forecaster:
    checkpoint_path: ${checkpoint}
    leadtimes: 25

frequency: 5m
inference_num_chunks: ${inference_num_chunks}
workdir: ${workdir}

datasets:
  meps:
    dataset: ${meps_zarr}
    start: ${meps_start_iso}
    end: ${meps_end_iso}
    frequency: 1h
    select: [t2m, tp, lcc, lsm, mcc, msl, z, u10, v10, cape, cin, d2m, wind_gust_10m]
    rename: {t2m: 2t, u10: 10u, v10: 10v}
  nordic_radar:
    dataset: ${radar_dataset}
    select: [lwe_precipitation_rate]
  netatmo:
    dataset: ${netatmo_dataset}
    select: [ff, fg, dd, pr, ta, rr, rr_hourly, uu]
  lightning:
    dataset: ${lightning_dataset}
    select: [thunder_count]
dataloader:
  datamodule:
    _target_: bris.data.dataset.SparseZarrDataset
    _convert_: all
    dataset_input_offsets:
      meps: [0]
      nordic_radar: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
      netatmo: [8, 9, 10, 11, 12]
      lightning: [8, 9, 10, 11, 12]
    output_dataset_names: [nordic_radar, lightning]
    forecast_reference_frequency: 5m
  num_workers: ${dataloader_num_workers}
  prefetch_factor: ${dataloader_prefetch_factor}
  pin_memory: ${dataloader_pin_memory}
  persistent_workers: ${dataloader_persistent_workers}

hardware:
  num_gpus_per_node: 1
  num_gpus_per_model: 1
  num_nodes: 1
  num_members: ${num_members}

model:
  _target_: bris.model.SparseForecasterPredictor
  _convert_: all
  ensemble_seed: 2023

routing:
  - decoder_name: nordic_radar
    outputs:
      - netcdf:
          filename_pattern: ${workdir}/precipitation_%Y%m%dT%H%MZ.nc
          variables: [lwe_precipitation_rate]
          global_attributes:
            title: BRIS multisource ensemble precipitation nowcast
  - decoder_name: lightning
    outputs:
      - netcdf:
          filename_pattern: ${workdir}/lightning_logits_%Y%m%dT%H%MZ.nc
          variables: [thunder_count]
          global_attributes:
            title: BRIS multisource ensemble lightning logits
background_write: false
loglevel: info
